datasource:
  url: jdbc:mysql://localhost:3306/schooldb
  jdbcurl: jdbc:mysql://localhost:3306/schooldb?useTimezone=true&serverTimezone=UTC
  username: root
  password: itsasecret
  driverClassName: com.mysql.cj.jdbc.Driver